---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections: 
upload_dir: portfolio/.vuepress/public/upload
public_path: "/upload"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
